{% set name = "pytest-lazy-fixtures" %}
{% set version = "1.3.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pytest_lazy_fixtures-{{ version }}.tar.gz
  sha256: 7dd2c110830897b83f041d3a503cbdda10c98ced6dca7602fc43e2f6017c27ed

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }},<4.0.0
    - pytest >=7

test:
  imports:
    - pytest_lazy_fixtures
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/dev-petrov/pytest-lazy-fixtures
  summary: Allows you to use fixtures in @pytest.mark.parametrize.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jonashaag
