{% set name = "pytest-lazy-fixtures" %}
{% set version = "1.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pytest_lazy_fixtures-{{ version }}.tar.gz
  sha256: 0c561f0d29eea5b55cf29b9264a3241999ffdb74c6b6e8c4ccc0bd2c934d01ed

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8,<4.0
    - poetry-core
    - pip
  run:
    - python >=3.8.0,<4.0.0
    - pytest >=7

test:
  imports:
    - pytest_lazy_fixtures
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/dev-petrov/pytest-lazy-fixtures
  summary: Allows you to use fixtures in @pytest.mark.parametrize.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jonashaag
